[package]
name = "tin-can"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.168"
log = "0.4.22"
thiserror = "2.0.7"

[dev-dependencies]
simplelog = "0.12.2"

[features]
cap = []
map_uid_range = ["cap"]
default = []
